/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Pharmacist;


import java.text.SimpleDateFormat;
import java.util.Date;

import java.awt.CardLayout;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import network.Business;
import network.Drug.Drug;
import network.Drug.DrugCatalog;
import network.Model.User;
import network.Notification.Notification;
import network.Notification.NotificationDirectory;

/**
 *
 * @author SS
 */
public class ViewDrugCatalogJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    DrugCatalog drugCatalog;

    NotificationDirectory notificationDirectory;
    Business business;
    User authenticatedUser;
    /**
     * Creates new form ViewDrugCatalogJPanel
     */
    public ViewDrugCatalogJPanel(JPanel userProcessContainer, DrugCatalog drugCatalog, Business business,User user) {

        initComponents();

        this.userProcessContainer = userProcessContainer;

        
        this.notificationDirectory = business.getNotificationDirectory();
        this.authenticatedUser = user;
        

        this.drugCatalog = business.getDrugCatalog();


        populateDrugCatalogTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        drugCatalogTable = new javax.swing.JTable();
        btnRequestDrug = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setText("Drug Catalog");

        drugCatalogTable.setBackground(new java.awt.Color(153, 255, 255));
        drugCatalogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Drug ID", "Drug Name", "Price", "Availability"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(drugCatalogTable);

        btnRequestDrug.setText("Request Drug");
        btnRequestDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestDrugActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnBack)
                .addGap(231, 231, 231)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRequestDrug))
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnBack))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnRequestDrug)
                .addContainerGap(119, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestDrugActionPerformed
        // TODO add your handling code here:
         addNotificationForSelectedCategory();
        
        
    }//GEN-LAST:event_btnRequestDrugActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void populateDrugCatalogTable() {
        DefaultTableModel model = (DefaultTableModel) drugCatalogTable.getModel();
        model.setRowCount(0);

        for (Drug drug : drugCatalog.getDrugList()) {
            Object[] row = new Object[4];
            row[0] = drug.getDrugId();
            row[1] = drug.getDrugName();
            row[2] = drug.getPrice();
            row[3] = drug.getAvailablility();
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestDrug;
    private javax.swing.JTable drugCatalogTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    private void addNotificationForSelectedCategory() {
        String drugName;
        int selectedRow = drugCatalogTable.getSelectedRow(); // Get the selected row index

        if (selectedRow != -1) { // Ensure a row is selected
           DefaultTableModel model = (DefaultTableModel) drugCatalogTable.getModel();
          drugName = (String) model.getValueAt(selectedRow, 1); // Column index 1 for DrugName
          //System.out.println("Selected Drug Name: " + drugName);
        } else {
         JOptionPane.showMessageDialog(this, "Please select a Drug first.", "Warning", JOptionPane.WARNING_MESSAGE);

            return;
        }

    // Get the current timestamp
    String currentTimestamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());

    // Create a new notification
    Notification notification = new Notification(
        "Increase Stock",                        // Status
        currentTimestamp,                   // Timestamp
        authenticatedUser.getRole(),        // FromRole
        "Admin",                            // ToRole
        drugName                   // Regarding
    );

    // Add the notification to the NotificationDirectory
    notificationDirectory.addNewNotification(notification);

    // Confirmation message
    JOptionPane.showMessageDialog(this, "Request sent to Admin to Increase the stock", "Notification", JOptionPane.INFORMATION_MESSAGE);
        
    }
}
