/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Patient;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import network.Complaint.Complaint;
import network.Complaint.ComplaintDirectory;
import network.Model.HealthCareProfessional;
import network.Model.HealthCareProfessionalDirectory;
import network.Model.Patient;
import network.Model.Specialist;
import network.Model.SpecialistDirectory;
import network.Model.User;
import network.Model.UserDirectory;

/**
 *
 * @author Abhishek Patil
 */
public class RegisterComplaintJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserDirectory userDirectory;
    ComplaintDirectory complaintDirectory;
    HealthCareProfessionalDirectory healthCareProfessionalDirectory;
    SpecialistDirectory specialistDirectory;
    
    /**
     * Creates new form RegisterComplaintJPanel
     */
    public RegisterComplaintJPanel(JPanel userProcessContainer, UserDirectory userDirectory, ComplaintDirectory complaintDirectory, 
            HealthCareProfessionalDirectory healthCareProfessionalDirectory, SpecialistDirectory specialistDirectory) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userDirectory = userDirectory;
        this.complaintDirectory = complaintDirectory;
        this.healthCareProfessionalDirectory = healthCareProfessionalDirectory;
        this.specialistDirectory = specialistDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEmail = new javax.swing.JTextField();
        lblPriorityLevel = new javax.swing.JLabel();
        btnAddVitals = new javax.swing.JButton();
        txtPatientName = new javax.swing.JTextField();
        cmbComplaintType = new javax.swing.JComboBox<>();
        lblPatientId = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        txtPatientAge = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblPatientAge = new javax.swing.JLabel();
        lblMedicalHistory = new javax.swing.JLabel();
        lblComplaintId = new javax.swing.JLabel();
        txtComplaintId = new javax.swing.JTextField();
        lblComplaintType = new javax.swing.JLabel();
        btnVitals2 = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblPatientGender = new javax.swing.JLabel();
        txtPatientId = new javax.swing.JTextField();
        txtCondition = new javax.swing.JTextField();
        lblComplaint = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        txtPatientGender = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtMedicalHistory = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        cmbPriorityLevel = new javax.swing.JComboBox<>();

        lblPriorityLevel.setText("Priority Level");

        btnAddVitals.setText("Add Vitals");
        btnAddVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVitalsActionPerformed(evt);
            }
        });

        cmbComplaintType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblPatientId.setText("Patient ID:");

        lblPatientName.setText("Patient Name:");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblPatientAge.setText("Patient Age:");

        lblMedicalHistory.setText("Medication History:");

        lblComplaintId.setText("Complaint ID:");

        lblComplaintType.setText("Complaint Type");

        btnVitals2.setText("<<Back");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("New Complaint");

        lblPatientGender.setText("Patient Gender:");

        lblComplaint.setText("Condition:");

        lblPhoneNumber.setText("Phone Number:");

        lblEmail.setText("Email");

        lblDescription.setText("Description:");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        cmbPriorityLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnVitals2)
                .addGap(255, 255, 255)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblComplaintType)
                            .addComponent(lblComplaintId)
                            .addComponent(lblPriorityLevel)
                            .addComponent(lblComplaint)
                            .addComponent(lblMedicalHistory)
                            .addComponent(lblDescription))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPhoneNumber))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMedicalHistory)
                                    .addComponent(txtCondition)
                                    .addComponent(cmbComplaintType, 0, 138, Short.MAX_VALUE)
                                    .addComponent(cmbPriorityLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtComplaintId, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPatientId, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPatientName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPatientAge, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPatientGender, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPatientId, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(txtPatientName)
                            .addComponent(txtPatientAge)
                            .addComponent(txtPatientGender)
                            .addComponent(txtEmail)
                            .addComponent(txtPhoneNumber)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddVitals)
                        .addGap(30, 30, 30)
                        .addComponent(btnSubmit)))
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVitals2)
                    .addComponent(lblTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblComplaint)
                            .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail)
                            .addComponent(lblMedicalHistory)
                            .addComponent(txtMedicalHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPhoneNumber)
                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDescription))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblComplaintId)
                            .addComponent(txtComplaintId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPatientId)
                            .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPatientName)
                            .addComponent(cmbComplaintType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComplaintType))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPriorityLevel)
                                .addComponent(cmbPriorityLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPatientAge)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPatientGender)
                            .addComponent(txtPatientGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnAddVitals))
                .addGap(97, 97, 97))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVitalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddVitalsActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        // Collecting data from the form fields
        String description = txtDescription.getText();
        String priority = (String) cmbPriorityLevel.getSelectedItem();
        String complaintType = (String) cmbComplaintType.getSelectedItem();
        String patientName = txtPatientName.getText();
        String patientGender = txtPatientGender.getText();
        String patientAge = txtPatientAge.getText();
        String condition = txtCondition.getText();
        String phoneNumber = txtPhoneNumber.getText();
        String email = txtEmail.getText();
        
        // Create new Patient object
        Patient newPatient = new Patient("patient" + (userDirectory.getUserList().size() + 1), "password", "", patientName, patientGender, patientAge, condition, phoneNumber, email, medicationHistory);
        
        // Create new Complaint object
        Complaint newComplaint = new Complaint(complaintDirectory.generateComplaintId(), description, priority, complaintType, newPatient);

        // Add complaint to complaint directory
        complaintDirectory.addComplaint(newComplaint);

        // Optionally, add the patient to the user directory
        userDirectory.addUser(newPatient);
        
        // Optionally, assign complaint to health care professionals or specialists based on type/priority
        if ("Critical".equals(priority) || "Medical Emergency".equals(complaintType)) {
            // Assign to specialists
            for (Specialist specialist : specialistDirectory.getSpecialistList()) {
                specialist.addComplaint(newComplaint);
            }
        } else {
            // Assign to healthcare professionals
            for (HealthCareProfessional hcp : healthCareProfessionalDirectory.getHealthCareProfessionalList()) {
                hcp.addComplaint(newComplaint);
            }
        }

        // Display success message
        JOptionPane.showMessageDialog(this, "Complaint registered successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        // Clear the form fields after submission
        clearFields();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void clearFields() {
        txtDescription.setText("");
        cmbPriorityLevel.setSelectedIndex(0);
        cmbComplaintType.setSelectedIndex(0);
        txtPatientName.setText("");
        txtPatientGender.setText("");
        txtPatientAge.setText("");
        txtCondition.setText("");
        txtPhoneNumber.setText("");
        txtEmail.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVitals;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnVitals2;
    private javax.swing.JComboBox<String> cmbComplaintType;
    private javax.swing.JComboBox<String> cmbPriorityLevel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblComplaint;
    private javax.swing.JLabel lblComplaintId;
    private javax.swing.JLabel lblComplaintType;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMedicalHistory;
    private javax.swing.JLabel lblPatientAge;
    private javax.swing.JLabel lblPatientGender;
    private javax.swing.JLabel lblPatientId;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPriorityLevel;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtComplaintId;
    private javax.swing.JTextField txtCondition;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMedicalHistory;
    private javax.swing.JTextField txtPatientAge;
    private javax.swing.JTextField txtPatientGender;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
