/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Patient;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import network.Business;
import network.Complaint.Complaint;
import network.Medication.Medication;
import network.Medication.MedicationOrder;
import network.Model.User;
import network.Treatment.Assessment;
import network.Treatment.AssessmentDirectory;

/**
 *
 * @author Abhishek Patil
 */
public class ViewComplaintJPanel extends javax.swing.JPanel {
    Complaint complaint;
    Business business;
    User authenticatedUser;
    AssessmentDirectory assessmentDirectory;
    

    /**
     * Creates new form ViewComplaintJPanel
     */
    public ViewComplaintJPanel(JPanel userProcessContainer, Complaint complaint, Business business, User user) {
        initComponents();
        this.complaint = complaint;
        this.business = business;
        this.authenticatedUser = user;
        this.assessmentDirectory = business.getAssessmentDirectory();
        
        
        
        populateFields();
        populateMedicationTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDescription = new javax.swing.JTextField();
        lblComplaintId2 = new javax.swing.JLabel();
        btnVitals1 = new javax.swing.JButton();
        lblComplaintId5 = new javax.swing.JLabel();
        txtAssignedTo = new javax.swing.JTextField();
        txtAssessmentReview = new javax.swing.JTextField();
        lblComplaintId6 = new javax.swing.JLabel();
        lblComplaintId3 = new javax.swing.JLabel();
        lblComplaintId = new javax.swing.JLabel();
        txtDateSubmitted = new javax.swing.JTextField();
        txtComplaintId = new javax.swing.JTextField();
        lblComplaintId8 = new javax.swing.JLabel();
        lblComplaintId4 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtTreatmentPlan = new javax.swing.JTextField();
        lblComplaintId9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedication = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblComplaintId7 = new javax.swing.JLabel();
        txtTotalFees = new javax.swing.JTextField();
        lblComplaintId10 = new javax.swing.JLabel();
        txtMedicationOrderStatus = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblComplaintId11 = new javax.swing.JLabel();
        txtOrderId = new javax.swing.JTextField();

        lblComplaintId2.setText("Status");

        btnVitals1.setText("Claim Insurance");

        lblComplaintId5.setText("Description");

        lblComplaintId6.setText("Assisment Review");

        lblComplaintId3.setText("AssignedTo");

        lblComplaintId.setText("Complaint ID*");

        lblComplaintId8.setText("Drugs Prescribed");

        lblComplaintId4.setText("DateSubmitted");

        txtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusActionPerformed(evt);
            }
        });

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblComplaintId9.setText("TreatmentPlan");

        tblMedication.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DrugID", "DrugName", "Dosage", "Frequency"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMedication);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Complaint Details");

        lblComplaintId7.setText("Fees");

        lblComplaintId10.setText("Approved by pharma");

        jLabel2.setText("<Set value=Assismentfees+medicationorderFees>");

        lblComplaintId11.setText("OrderID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lblComplaintId8)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblComplaintId)
                            .addComponent(lblComplaintId2)
                            .addComponent(lblComplaintId5)
                            .addComponent(lblComplaintId6)
                            .addComponent(lblComplaintId9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(txtComplaintId, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblComplaintId3)
                                    .addComponent(lblComplaintId4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(txtAssignedTo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDateSubmitted, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTreatmentPlan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtDescription)
                                        .addComponent(txtAssessmentReview, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton1)
                        .addGap(247, 247, 247)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(lblComplaintId7)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalFees, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(btnVitals1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblComplaintId11)
                        .addGap(18, 18, 18)
                        .addComponent(txtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lblComplaintId10)
                        .addGap(18, 18, 18)
                        .addComponent(txtMedicationOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComplaintId)
                    .addComponent(txtComplaintId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComplaintId3)
                    .addComponent(txtAssignedTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComplaintId4)
                    .addComponent(txtDateSubmitted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComplaintId2)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComplaintId5)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComplaintId6)
                    .addComponent(txtAssessmentReview, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComplaintId9)
                    .addComponent(txtTreatmentPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComplaintId8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComplaintId10)
                    .addComponent(txtMedicationOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComplaintId11)
                    .addComponent(txtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComplaintId7)
                    .addComponent(txtTotalFees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(14, 14, 14)
                .addComponent(btnVitals1)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVitals1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblComplaintId;
    private javax.swing.JLabel lblComplaintId10;
    private javax.swing.JLabel lblComplaintId11;
    private javax.swing.JLabel lblComplaintId2;
    private javax.swing.JLabel lblComplaintId3;
    private javax.swing.JLabel lblComplaintId4;
    private javax.swing.JLabel lblComplaintId5;
    private javax.swing.JLabel lblComplaintId6;
    private javax.swing.JLabel lblComplaintId7;
    private javax.swing.JLabel lblComplaintId8;
    private javax.swing.JLabel lblComplaintId9;
    private javax.swing.JTable tblMedication;
    private javax.swing.JTextField txtAssessmentReview;
    private javax.swing.JTextField txtAssignedTo;
    private javax.swing.JTextField txtComplaintId;
    private javax.swing.JTextField txtDateSubmitted;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtMedicationOrderStatus;
    private javax.swing.JTextField txtOrderId;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTotalFees;
    private javax.swing.JTextField txtTreatmentPlan;
    // End of variables declaration//GEN-END:variables

    private void populateFields() {
        // Populate the fields with data from the complaint and authenticated user (Patient)

    // Set complaint fields
    txtComplaintId.setText(complaint.getComplaintId());
    txtDescription.setText(complaint.getDescription());
    txtAssignedTo.setText(complaint.getAssignedTo());
    txtDateSubmitted.setText(String.valueOf(complaint.getTimestamp()));
    txtStatus.setText(complaint.getStatus());
   

    // Set assessment-related fields from the complaint
    Assessment assessment = assessmentDirectory.getAssessmentByComplaintId(complaint.getComplaintId());
    if (assessment != null) {
        txtAssessmentReview.setText(assessment.getAssessmentReview());
        txtTotalFees.setText(String.valueOf(assessment.getTotalFees()));
        txtTreatmentPlan.setText(assessment.getTreatmentPlan());
    }

    // Set medication order status and order ID from the complaint's associated medication order
    //MedicationOrder medicationOrder = complaint.getMedicationOrder();
    //if (medicationOrder != null) {
    //    txtOrderId.setText(medicationOrder.getOrderId());
    //    txtMedicationOrderStatus.setText(medicationOrder.getStatus());
    //}
        
        
    }

    private void populateMedicationTable() {
        // Populate the medication table with prescribed medications from the patient's assessment
    Assessment assessment = assessmentDirectory.getAssessmentByComplaintId(complaint.getComplaintId());
    if (assessment != null && assessment.getMedicationsList() != null) {
        DefaultTableModel model = (DefaultTableModel) tblMedication.getModel();
        model.setRowCount(0); // Clear any existing data in the table

        for (Medication medication : assessment.getMedicationsList()) {
            Object[] row = new Object[4];
            row[0] = medication.getDrugId();
            row[1] = medication.getDrugName();
            row[2] = medication.getDosage();
            row[3] = medication.getFrequency();
            model.addRow(row); // Add row for each medication
        }
    }
        
        
    }
}
