/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import network.Model.HealthCareProfessional;
import network.Model.Specialist;
import network.Model.UserDirectory;

/**
 *
 * @author Abhishek Patil
 */
public class AddHCPsJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer; 
    UserDirectory userDirectory;
    String selectedRole;

    /**
     * Creates new form AddHCPsJPanel
     */
    public AddHCPsJPanel(JPanel userProcessContainer, UserDirectory userDirectory) {
        initComponents();
        this.userDirectory = userDirectory;
        this.userProcessContainer = userProcessContainer;
        
        cmbRole.removeAll();
        cmbRole.addItem("HealthCareProfessional");
        cmbRole.addItem("Specialist");
        
       
        txtHEmail.setEnabled(false);
        txtHID.setEnabled(false);
        txtHName.setEnabled(false);
        txtHPassword.setEnabled(false);
        txtHSpecialization.setEnabled(false);
        txtHUserID.setEnabled(false);
        txtHUserName.setEnabled(false);
        btnHSave.setEnabled(false);
        
        txtSEmail.setEnabled(false);
        txtSID.setEnabled(false);
        txtSName.setEnabled(false);
        txtSPassword.setEnabled(false);
        txtSSpecialization.setEnabled(false);
        txtSUserId.setEnabled(false);
        txtSUserName.setEnabled(false);
        btnSSave.setEnabled(false);
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHuserID = new javax.swing.JLabel();
        txtHUserID = new javax.swing.JTextField();
        lblHUserName = new javax.swing.JLabel();
        txtHUserName = new javax.swing.JTextField();
        txtHPassword = new javax.swing.JTextField();
        lblHPassword = new javax.swing.JLabel();
        txtHSpecialization = new javax.swing.JTextField();
        lblHSpecialization = new javax.swing.JLabel();
        lblHID = new javax.swing.JLabel();
        txtHID = new javax.swing.JTextField();
        lblHName = new javax.swing.JLabel();
        txtHName = new javax.swing.JTextField();
        lblHemail = new javax.swing.JLabel();
        txtHEmail = new javax.swing.JTextField();
        cmbRole = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSSpecialization = new javax.swing.JTextField();
        lblSSpecialization = new javax.swing.JLabel();
        lblSID = new javax.swing.JLabel();
        txtSID = new javax.swing.JTextField();
        lblSName = new javax.swing.JLabel();
        lblSUserID = new javax.swing.JLabel();
        txtSName = new javax.swing.JTextField();
        txtSUserId = new javax.swing.JTextField();
        lblSEmail = new javax.swing.JLabel();
        lblSUserName = new javax.swing.JLabel();
        txtSEmail = new javax.swing.JTextField();
        txtSUserName = new javax.swing.JTextField();
        txtSPassword = new javax.swing.JTextField();
        lblSPassword = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnHSave = new javax.swing.JButton();
        btnSSave = new javax.swing.JButton();
        btnGo = new javax.swing.JButton();

        lblHuserID.setText("UserID");

        lblHUserName.setText("UserName");

        lblHPassword.setText("Password");

        lblHSpecialization.setText("Specialization");

        lblHID.setText("HCP ID");

        txtHID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHIDActionPerformed(evt);
            }
        });

        lblHName.setText("Name");

        txtHName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHNameActionPerformed(evt);
            }
        });

        lblHemail.setText("Email");

        txtHEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHEmailActionPerformed(evt);
            }
        });

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Select Role");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("HealthCareProfessional");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Specialist");

        lblSSpecialization.setText("Specialization");

        lblSID.setText("Specialist ID");

        txtSID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSIDActionPerformed(evt);
            }
        });

        lblSName.setText("Name");

        lblSUserID.setText("UserID");

        txtSName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSNameActionPerformed(evt);
            }
        });

        lblSEmail.setText("Email");

        lblSUserName.setText("UserName");

        txtSEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSEmailActionPerformed(evt);
            }
        });

        lblSPassword.setText("Password");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnHSave.setText("Save");
        btnHSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHSaveActionPerformed(evt);
            }
        });

        btnSSave.setText("Save");
        btnSSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSSaveActionPerformed(evt);
            }
        });

        btnGo.setText("Go");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnBack)
                        .addGap(115, 115, 115)
                        .addComponent(jLabel8)
                        .addGap(20, 20, 20)
                        .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHSpecialization)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblHPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblHUserName)
                                        .addComponent(lblHuserID)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtHSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtHUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHID)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblHemail))
                                    .addComponent(lblHName)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSSpecialization)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblSPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblSUserName)
                                        .addComponent(lblSUserID)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtSSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtSUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSID)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblSEmail))
                                    .addComponent(lblSName))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtHID)
                            .addComponent(txtHName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSID, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSName, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSSave)
                            .addComponent(btnHSave)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel9)))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtHPassword, txtHSpecialization, txtHUserID, txtHUserName, txtSPassword, txtSSpecialization, txtSUserId, txtSUserName});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtHEmail, txtHID, txtHName, txtSEmail, txtSID, txtSName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(btnGo)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHID)
                            .addComponent(txtHID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHName)
                            .addComponent(txtHName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHemail)
                            .addComponent(txtHEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHuserID)
                            .addComponent(txtHUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHUserName)
                            .addComponent(txtHUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHPassword)
                            .addComponent(txtHPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHSpecialization)
                            .addComponent(txtHSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSID)
                            .addComponent(txtSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSName)
                            .addComponent(txtSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSEmail)
                            .addComponent(txtSEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSUserID)
                            .addComponent(txtSUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSUserName)
                            .addComponent(txtSUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSPassword)
                            .addComponent(txtSPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSSpecialization)
                            .addComponent(txtSSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSSave)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHIDActionPerformed

    private void txtHNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHNameActionPerformed

    private void txtHEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHEmailActionPerformed

    private void txtSIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSIDActionPerformed

    private void txtSNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSNameActionPerformed

    private void txtSEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSEmailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component [] componentArray = userProcessContainer.getComponents();
        Component c = componentArray[componentArray.length-1];
        ManageEmployeJPanel ms = (ManageEmployeJPanel) c;
        ms.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        // TODO add your handling code here:
        selectedRole= (String) cmbRole.getSelectedItem();
         fillForm();
        
    }//GEN-LAST:event_btnGoActionPerformed

    private void btnHSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHSaveActionPerformed
        // TODO add your handling code here:
        String HEmail = txtHEmail.getText().trim();
    String HID = txtHID.getText().trim();
    String HName = txtHName.getText().trim();
    String HPassword = txtHPassword.getText().trim();
    String HSpecialization = txtHSpecialization.getText().trim();
    String HUserID = txtHUserID.getText().trim();
    String HUserName = txtHUserName.getText().trim();

    // Check if any field is empty
    if (HEmail.isEmpty() || HID.isEmpty() || HName.isEmpty() || HPassword.isEmpty() || 
        HSpecialization.isEmpty() || HUserID.isEmpty() || HUserName.isEmpty()) {

        JOptionPane.showMessageDialog(this, "Please fill in all fields before saving.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Add the healthcare professional to the directory
    userDirectory.addUser(new HealthCareProfessional(HUserID, HUserName, HPassword, HSpecialization, HID, HName, HEmail));
    JOptionPane.showMessageDialog(this, "Health Care Professional Successfully added", "Message", JOptionPane.INFORMATION_MESSAGE);
    txtHID.setText("");
    txtHName.setText("");
    txtHPassword.setText("");
    txtHSpecialization.setText("");
    txtHUserID.setText("");
    txtHUserName.setText("");
    
    
    }//GEN-LAST:event_btnHSaveActionPerformed

    private void btnSSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSSaveActionPerformed
        // TODO add your handling code here:
        String SEmail = txtSEmail.getText().trim();
        String SID = txtSID.getText().trim();
        String SName = txtSName.getText().trim();
                
        String SPassword = txtSPassword.getText().trim();
        String SSpecialization= txtSSpecialization.getText().trim();
        String SUserID=txtSUserId.getText().trim();
        String SUserName = txtSUserName.getText().trim();
        
        
        if (SEmail.isEmpty() || SID.isEmpty() || SName.isEmpty() || SPassword.isEmpty() || 
        SSpecialization.isEmpty() || SUserID.isEmpty() || SUserName.isEmpty()) {

        JOptionPane.showMessageDialog(this, "Please fill in all fields before saving.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }
        
        userDirectory.addUser(new Specialist(SUserID,SUserName,SPassword,SID,SName,SSpecialization,SEmail));
        
        JOptionPane.showMessageDialog(this, "Specialist Successfully added", "message", JOptionPane.INFORMATION_MESSAGE);
        
        txtSEmail.setText("");
         txtSID.setText("");
        txtSName.setText("");
                
        txtSPassword.setText("");
        txtSSpecialization.setText("");
        txtSUserId.setText("");
        txtSUserName.setText("");
        
    }//GEN-LAST:event_btnSSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnHSave;
    private javax.swing.JButton btnSSave;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblHID;
    private javax.swing.JLabel lblHName;
    private javax.swing.JLabel lblHPassword;
    private javax.swing.JLabel lblHSpecialization;
    private javax.swing.JLabel lblHUserName;
    private javax.swing.JLabel lblHemail;
    private javax.swing.JLabel lblHuserID;
    private javax.swing.JLabel lblSEmail;
    private javax.swing.JLabel lblSID;
    private javax.swing.JLabel lblSName;
    private javax.swing.JLabel lblSPassword;
    private javax.swing.JLabel lblSSpecialization;
    private javax.swing.JLabel lblSUserID;
    private javax.swing.JLabel lblSUserName;
    private javax.swing.JTextField txtHEmail;
    private javax.swing.JTextField txtHID;
    private javax.swing.JTextField txtHName;
    private javax.swing.JTextField txtHPassword;
    private javax.swing.JTextField txtHSpecialization;
    private javax.swing.JTextField txtHUserID;
    private javax.swing.JTextField txtHUserName;
    private javax.swing.JTextField txtSEmail;
    private javax.swing.JTextField txtSID;
    private javax.swing.JTextField txtSName;
    private javax.swing.JTextField txtSPassword;
    private javax.swing.JTextField txtSSpecialization;
    private javax.swing.JTextField txtSUserId;
    private javax.swing.JTextField txtSUserName;
    // End of variables declaration//GEN-END:variables

    private void fillForm() {
        
        
        if (selectedRole.equals("HealthCareProfessional")){
        
            
            
        txtHEmail.setEnabled(true);
        txtHID.setEditable(true);
        txtHName.setEnabled(true);
        txtHPassword.setEnabled(true);
        txtHSpecialization.setEnabled(true);
        txtHUserID.setEnabled(true);
        txtHUserName.setEnabled(true);
        btnHSave.setEnabled(true);
        
        
        
        
            
        }
        if (selectedRole.equals("Specialist")){
        
            
            
        txtSEmail.setEnabled(true);
        txtSID.setEditable(true);
        txtSName.setEnabled(true);
        txtSPassword.setEnabled(true);
        txtSSpecialization.setEnabled(true);
        txtSUserId.setEnabled(true);
        txtSUserName.setEnabled(true);
        btnSSave.setEnabled(true);
            
        }
            
        
    }
}
