/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import network.Business;
import network.Drug.DrugCatalog;
import network.Enterprise.EnterpriseDirectory;
import network.Model.UserDirectory;
import network.Organization.OrganizationDirectory;
import network.Reports.Report;
import network.Reports.ReportDirectory;

/**
 *
 * @author Abhishek Patil
 */
public class ManageReportsJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    String reportCat;
    ReportDirectory reportDirectory;
    DrugCatalog drugDirectory;
    UserDirectory userDirectory;
    OrganizationDirectory organizationDirectory;
    Business business;
    EnterpriseDirectory enterpriseDirectory;

    /**
     * Creates new form ManageReportsJPanel
     */
    public ManageReportsJPanel(JPanel userProcessContainer, Business bus) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        
        this.business = bus;
        this.reportDirectory = business.getReportDirectory();
        this.drugDirectory = business.getDrugCatalog();
        this.userDirectory = business.getUserDirectory();
        this.organizationDirectory = business.getOrganizationDirectory();
        this.enterpriseDirectory = business.getEnterpriseDirectory();
        
        cmbReportCat.removeAll();
        cmbReportCat.addItem("OrganizationList");
        cmbReportCat.addItem("DrugReport");
        cmbReportCat.addItem("HCPReport");
        cmbReportCat.addItem("PatientReport");
        
        //reportCat=(String) cmbReportCat.getSelectedItem();
        
        cmbSendTo.removeAll();
        cmbSendTo.addItem("Auditors");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        cmbSendTo = new javax.swing.JComboBox<>();
        lblSendReportTo = new javax.swing.JLabel();
        cmbReportCat = new javax.swing.JComboBox<>();
        lblFetchOrganization = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGeneratedReport = new javax.swing.JTable();
        btnGenerate = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Manage Reports");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cmbSendTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSendReportTo.setText("Send Reports To");

        cmbReportCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblFetchOrganization.setText("Fetch Report of Category");

        btnSend.setText("Send");

        btnView.setText("View");

        tblGeneratedReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblGeneratedReport);

        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnBack)
                        .addGap(187, 187, 187)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnView)
                                    .addComponent(lblSendReportTo))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbSendTo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSend)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFetchOrganization)
                                .addGap(63, 63, 63)
                                .addComponent(cmbReportCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGenerate))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblTitle))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbReportCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFetchOrganization)
                    .addComponent(btnGenerate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSendTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSendReportTo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSend)
                    .addComponent(btnView))
                .addGap(100, 100, 100))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        reportCat = (String) cmbReportCat.getSelectedItem();

    // Generate reports based on the subject
        reportDirectory.generateReportsBasedOnSubject(reportCat,userDirectory,drugDirectory,organizationDirectory,enterpriseDirectory );

    // Populate the table with generated reports
        populateTable();
        
        
        
    }//GEN-LAST:event_btnGenerateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> cmbReportCat;
    private javax.swing.JComboBox<String> cmbSendTo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFetchOrganization;
    private javax.swing.JLabel lblSendReportTo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblGeneratedReport;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblGeneratedReport.getModel();
        model.setRowCount(0); // Clear the table

    //String selectedSubject = (String) cmbReportCat.getSelectedItem();

    // Set dynamic column names
    switch (reportCat) {
        case "DrugReport":
            model.setColumnIdentifiers(new Object[]{"ReportID", "DrugID", "DrugName", "Quantity", "ExpDate"});
            break;

        case "HCPReport":
            model.setColumnIdentifiers(new Object[]{"ReportID", "HealthCareProfessionalID", "Name", "No. of Complaints Handled", "Years of Experience"});
            break;

        case "PatientReport":
            model.setColumnIdentifiers(new Object[]{"ReportID", "PatientID", "Name", "No. of Complaints Registered", "No. of Complaints Resolved"});
            break;

        case "OrganizationList":
            model.setColumnIdentifiers(new Object[]{"ReportID", "OrganizationID", "Name", "EnterpriseName", "No. of Users"});
            break;

        default:
            System.out.println("Invalid subject selected.");
            return;
    }

    // Add rows to the table
    for (Report report : reportDirectory.getReports()) {
        model.addRow(new Object[]{
            report.getReportID(),
            report.getSubjectID(),
            report.getSubjectName(),
            report.getSubjectQ1(),
            report.getSubjectQ2()
        });
    }
        
        
    }
}
