/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import java.awt.CardLayout;
import javax.swing.JPanel;
import network.Enterprise.HealthCareEnterprise;
import network.Model.HealthCareProfessional;
import network.Model.Specialist;
import network.Model.User;
import network.Model.UserDirectory;

/**
 *
 * @author Abhishek Patil
 */
public class ViewHCPJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer; 
    User selectedUser;
    HealthCareProfessional healthCareProfessional;
    Specialist specialist;
    /**
     * Creates new form ViewHCPJPanel
     */
    public ViewHCPJPanel(JPanel userProcessContainer, User selecteduser) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.selectedUser = selecteduser;
        
        lblTitle.setText(selectedUser.getRole());
        
        if(selectedUser.getRole().equals("HCP")){
        
            healthCareProfessional = (HealthCareProfessional) selectedUser;
            populateHCPFields();
        }else{
        
            specialist = (Specialist) selectedUser;
            populateHCPSFields();
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHSpecialization = new javax.swing.JTextField();
        lblHSpecialization = new javax.swing.JLabel();
        lblHID = new javax.swing.JLabel();
        txtHID = new javax.swing.JTextField();
        lblHName = new javax.swing.JLabel();
        txtHName = new javax.swing.JTextField();
        lblHemail = new javax.swing.JLabel();
        txtHEmail = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblHuserID = new javax.swing.JLabel();
        txtHUserID = new javax.swing.JTextField();
        lblHUserName = new javax.swing.JLabel();
        txtHUserName = new javax.swing.JTextField();
        txtHPassword = new javax.swing.JTextField();
        lblHPassword = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        lblHSpecialization.setText("Specialization");

        lblHID.setText("Professional ID");

        txtHID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHIDActionPerformed(evt);
            }
        });

        lblHName.setText("Name");

        txtHName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHNameActionPerformed(evt);
            }
        });

        lblHemail.setText("Email");

        txtHEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHEmailActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setText("<title>");

        lblHuserID.setText("UserID");

        lblHUserName.setText("UserName");

        lblHPassword.setText("Password");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHuserID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHUserName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHSpecialization, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHemail, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtHUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHID, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(269, 269, 269))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(260, 260, 260))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtHEmail, txtHID, txtHName, txtHPassword, txtHSpecialization, txtHUserID, txtHUserName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnBack)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHuserID)
                    .addComponent(txtHUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHUserName)
                    .addComponent(txtHUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHPassword)
                    .addComponent(txtHPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHSpecialization)
                    .addComponent(txtHSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHID)
                    .addComponent(txtHID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHName)
                    .addComponent(txtHName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHemail)
                    .addComponent(txtHEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHIDActionPerformed

    private void txtHNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHNameActionPerformed

    private void txtHEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHEmailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblHID;
    private javax.swing.JLabel lblHName;
    private javax.swing.JLabel lblHPassword;
    private javax.swing.JLabel lblHSpecialization;
    private javax.swing.JLabel lblHUserName;
    private javax.swing.JLabel lblHemail;
    private javax.swing.JLabel lblHuserID;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtHEmail;
    private javax.swing.JTextField txtHID;
    private javax.swing.JTextField txtHName;
    private javax.swing.JTextField txtHPassword;
    private javax.swing.JTextField txtHSpecialization;
    private javax.swing.JTextField txtHUserID;
    private javax.swing.JTextField txtHUserName;
    // End of variables declaration//GEN-END:variables

    

    private void populateHCPFields() {
        txtHEmail.setText(healthCareProfessional.getEmail());
     txtHID.setText(healthCareProfessional.getProfessionalId());
     txtHName.setText(healthCareProfessional.getName());
     txtHPassword.setText(healthCareProfessional.getPassword());
     txtHSpecialization.setText(healthCareProfessional.getSpecialization());
     txtHUserID.setText(selectedUser.getUserId());
     txtHUserName.setText(selectedUser.getUserName());
        
        
    }

    private void populateHCPSFields() {
        txtHEmail.setText(specialist.getEmail());
     txtHID.setText(specialist.getSpecialistId());
     txtHName.setText(specialist.getName());
     txtHPassword.setText(specialist.getPassword());
     txtHSpecialization.setText(specialist.getSpecialty());
     txtHUserID.setText(selectedUser.getUserId());
     txtHUserName.setText(selectedUser.getUserName());
        
    }
}
