/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Specialist;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import network.Complaint.Complaint;
import network.Medication.Medication;

import javax.swing.JPanel;

import java.util.ArrayList;

import javax.swing.JPanel;

import network.Medication.Medication;
import network.Treatment.Assessment;

/**
 *
 * @author SS
 */
public class AddAssessmentJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Complaint selectedComplaint;
    private ArrayList<Medication> medicationsList;

    /**
     * Creates new form AddAssessmentJPanel
     */
    public AddAssessmentJPanel(JPanel userProcessContainer, Complaint selectedComplaint) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.medicationsList = new ArrayList<>();
        this.selectedComplaint = selectedComplaint;

        populateMedicationTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAssessmentEvaluation = new javax.swing.JLabel();
        lblMedication = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSendNotifications = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblAssessmentReview = new javax.swing.JLabel();
        lblTreatmentPlan = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAssessmentReview = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTreatmentPlan = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicationsTable = new javax.swing.JTable();
        btnAddDrugs = new javax.swing.JButton();
        btnUpdateDrugs = new javax.swing.JButton();
        btnDeleteDrugs = new javax.swing.JButton();
        lblTotalFees = new javax.swing.JLabel();
        txtTotalFees = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        lblAssessmentEvaluation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAssessmentEvaluation.setText("Assessment Evaluation:");

        lblMedication.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMedication.setText("Medication:");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSendNotifications.setText("Send Notification");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setText("Assessment");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblAssessmentReview.setText("Assessment Review:");

        lblTreatmentPlan.setText("Treatment Plan:");

        txtAssessmentReview.setBackground(new java.awt.Color(242, 242, 242));
        txtAssessmentReview.setColumns(20);
        txtAssessmentReview.setRows(5);
        jScrollPane2.setViewportView(txtAssessmentReview);

        txtTreatmentPlan.setBackground(new java.awt.Color(242, 242, 242));
        txtTreatmentPlan.setColumns(20);
        txtTreatmentPlan.setRows(5);
        jScrollPane3.setViewportView(txtTreatmentPlan);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAssessmentReview)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblTreatmentPlan)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssessmentReview)
                    .addComponent(lblTreatmentPlan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(337, 337, 337))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblMedicationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Drug ID", "Drug Name", "Dosage", "Frequency"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMedicationsTable);

        btnAddDrugs.setText("Add");
        btnAddDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDrugsActionPerformed(evt);
            }
        });

        btnUpdateDrugs.setText("Update");
        btnUpdateDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDrugsActionPerformed(evt);
            }
        });

        btnDeleteDrugs.setText("Delete");
        btnDeleteDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDrugsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnAddDrugs)
                        .addGap(76, 76, 76)
                        .addComponent(btnUpdateDrugs)
                        .addGap(62, 62, 62)
                        .addComponent(btnDeleteDrugs))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDrugs)
                    .addComponent(btnUpdateDrugs)
                    .addComponent(btnDeleteDrugs))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTotalFees.setText("Total Fees:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(btnBack)
                            .addGap(242, 242, 242)
                            .addComponent(lblTitle))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(113, 113, 113)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTotalFees)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTotalFees, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSave)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnSendNotifications))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAssessmentEvaluation)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMedication))))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(btnBack))
                .addGap(32, 32, 32)
                .addComponent(lblAssessmentEvaluation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMedication)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSendNotifications)
                    .addComponent(lblTotalFees)
                    .addComponent(txtTotalFees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave))
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDrugsActionPerformed
        // TODO add your handling code here:
        AddMedicationJPanel amjp = new AddMedicationJPanel(userProcessContainer, medicationsList, medicationsList.size() + 1);
        userProcessContainer.add("AddMedicationJPanel", amjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddDrugsActionPerformed

    private void btnUpdateDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDrugsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMedicationsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a medication to update.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Medication medication = medicationsList.get(selectedRow);
        medication.setDrugName(JOptionPane.showInputDialog("Enter New Drug Name:", medication.getDrugName()));
        medication.setDosage(JOptionPane.showInputDialog("Enter New Dosage:", medication.getDosage()));
        medication.setFrequency(JOptionPane.showInputDialog("Enter New Frequency:", medication.getFrequency()));

        populateMedicationTable();
    }//GEN-LAST:event_btnUpdateDrugsActionPerformed

    private void btnDeleteDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDrugsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMedicationsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a medication to delete.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        medicationsList.remove(selectedRow);

        populateMedicationTable();
    }//GEN-LAST:event_btnDeleteDrugsActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String assessmentReview = txtAssessmentReview.getText().trim();
        String treatmentPlan = txtTreatmentPlan.getText().trim();
        String totalFeesText = txtTotalFees.getText().trim();

        // Validate fields
        if (assessmentReview.isEmpty() || treatmentPlan.isEmpty() || totalFeesText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all the fields before saving.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double totalFees;
        try {
            totalFees = Double.parseDouble(totalFeesText); // Parse total fees as double
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for total fees.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Create an Assessment object
        Assessment assessment = new Assessment(assessmentReview, treatmentPlan, totalFees, medicationsList);

        // Simulate saving assessment and medication order
        System.out.println("Assessment Review: " + assessment.getAssessmentReview());
        System.out.println("Treatment Plan: " + assessment.getTreatmentPlan());
        System.out.println("Total Fees: $" + assessment.getTotalFees());

        for (Medication medication : assessment.getMedicationsList()) {
            System.out.println("Medication - Drug ID: " + medication.getDrugId() + ", Name: " + medication.getDrugName()
                    + ", Dosage: " + medication.getDosage() + ", Frequency: " + medication.getFrequency());
        }
        
        selectedComplaint.setStatus("Resolved");
        
        String role = "HCP-S";
        
        if (userProcessContainer.getComponent(userProcessContainer.getComponentCount() - 1) instanceof SpecialistWorkAreaJPanel) {
            SpecialistWorkAreaJPanel specialistWorkArea = (SpecialistWorkAreaJPanel) userProcessContainer.getComponent(userProcessContainer.getComponentCount() - 1);
            specialistWorkArea.populateComplaintTable(role); // Update the table after the status change
        }
        
        JOptionPane.showMessageDialog(this, "Assessment and Medications saved successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        // Simulate saving the updated complaint status (you can also save to the database or system here)
        System.out.println("Complaint ID: " + selectedComplaint.getComplaintId() + " status updated to: " + selectedComplaint.getStatus());

        // Clear the fields after saving
        txtAssessmentReview.setText("");
        txtTreatmentPlan.setText("");
        txtTotalFees.setText("");
        medicationsList.clear();
        populateMedicationTable();
    }//GEN-LAST:event_btnSaveActionPerformed

    public void populateMedicationTable() {
        DefaultTableModel model = (DefaultTableModel) tblMedicationsTable.getModel();
        model.setRowCount(0);

        for (Medication medication : medicationsList) {
            Object[] row = new Object[4];
            row[0] = medication.getDrugId();
            row[1] = medication.getDrugName();
            row[2] = medication.getDosage();
            row[3] = medication.getFrequency();

            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDrugs;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteDrugs;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSendNotifications;
    private javax.swing.JButton btnUpdateDrugs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAssessmentEvaluation;
    private javax.swing.JLabel lblAssessmentReview;
    private javax.swing.JLabel lblMedication;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalFees;
    private javax.swing.JLabel lblTreatmentPlan;
    private javax.swing.JTable tblMedicationsTable;
    private javax.swing.JTextArea txtAssessmentReview;
    private javax.swing.JTextField txtTotalFees;
    private javax.swing.JTextArea txtTreatmentPlan;
    // End of variables declaration//GEN-END:variables
}
