/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Specialist;

import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import network.Complaint.Complaint;
import network.Complaint.ComplaintDirectory;
import ui.HealthCareProfessional.ViewComplaintsJPanel;

/**
 *
 * @author SS
 */
public class SpecialistWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    ComplaintDirectory complaintDirectory;
    String role = "HCP-S";

    /**
     * Creates new form SpecialistWorkAreaJPanel
     */
    public SpecialistWorkAreaJPanel(JPanel userProcessContainer, ComplaintDirectory complaintDirectory) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.complaintDirectory = complaintDirectory;

        populateComplaintTable(role);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewComplaint = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        complaintsTable = new javax.swing.JTable();

        btnViewComplaint.setText("View Complaint");
        btnViewComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewComplaintActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setText("Patient Complaints");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        complaintsTable.setAutoCreateRowSorter(true);
        complaintsTable.setBackground(new java.awt.Color(153, 204, 255));
        complaintsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Complaint ID", "Patient ID", "Complaint Type", "Priority Level", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        complaintsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(complaintsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(589, 589, 589)
                            .addComponent(btnViewComplaint))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBack)
                            .addGap(194, 194, 194)
                            .addComponent(lblTitle))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(lblTitle))
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btnViewComplaint)
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewComplaintActionPerformed
        // TODO add your handling code here:
        int selectedRow = complaintsTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a complaint first!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String complaintId = (String) complaintsTable.getValueAt(selectedRow, 1);

        ViewComplaintsJPanel vcjp = new ViewComplaintsJPanel(userProcessContainer, complaintDirectory, complaintId);
        userProcessContainer.add("ViewComplaintsJPanel", vcjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnViewComplaintActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    public void populateComplaintTable(String role) {
        DefaultTableModel model = (DefaultTableModel) complaintsTable.getModel();
        model.setRowCount(0);

        List<Complaint> complaints = new ArrayList<>();

        if ("HCP-S".equalsIgnoreCase(role)) {
            complaints = complaintDirectory.getComplaintsForSpecialist();  // Get complaints for specialist (Critical)
        } else if ("HCP".equalsIgnoreCase(role)) {
            complaints = complaintDirectory.getComplaintsForHealthcareOrganization();  // Get other complaints
        }

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        for (Complaint complaint : complaints) {
            Object[] row = new Object[6];

            row[0] = sdf.format(complaint.getTimestamp());
            row[1] = complaint.getComplaintId();
            row[2] = complaint.getPatient().getPatientId();
            row[3] = complaint.getComplaintType();
            row[4] = complaint.getPriorityLevel();
            row[5] = complaint.getStatus();

            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewComplaint;
    private javax.swing.JTable complaintsTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
