/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Specialist;

import java.awt.CardLayout;
import javax.swing.JPanel;
import network.Complaint.VitalSigns;

/**
 *
 * @author SS
 */
public class ViewVitalsJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    VitalSigns vitalSigns;

    /**
     * Creates new form ViewVitalsJPanel
     */
    public ViewVitalsJPanel(JPanel userProcessContainer, VitalSigns vitalSigns) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.vitalSigns = vitalSigns;

        populateVitalSigns();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBloodPressure = new javax.swing.JTextField();
        txtHeartRate = new javax.swing.JTextField();
        txtBodyTemp = new javax.swing.JTextField();
        txtRespiratoryRate = new javax.swing.JTextField();
        txtOxygenSaturation = new javax.swing.JTextField();
        txtBloodSugarLevel = new javax.swing.JTextField();
        txtCholestrolLevel = new javax.swing.JTextField();
        lblHeight = new javax.swing.JLabel();
        txtEcgResult = new javax.swing.JTextField();
        lblWeight = new javax.swing.JLabel();
        lblBMI = new javax.swing.JLabel();
        lblPainLevel = new javax.swing.JLabel();
        lblCholestrolLevel = new javax.swing.JLabel();
        lblEcgResult = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtHeight = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        lblBloodPressure = new javax.swing.JLabel();
        txtBMI = new javax.swing.JTextField();
        lblHeartRate = new javax.swing.JLabel();
        txtPainLevel = new javax.swing.JTextField();
        lblBloodTemp = new javax.swing.JLabel();
        lblRespiratoryRate = new javax.swing.JLabel();
        lblOxygenSaturation = new javax.swing.JLabel();
        lblBloodSugarLevel = new javax.swing.JLabel();

        txtBloodPressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodPressureActionPerformed(evt);
            }
        });

        lblHeight.setText("Height:");

        lblWeight.setText("Weight:");

        lblBMI.setText("BMI:");

        lblPainLevel.setText("Pain Level:");

        lblCholestrolLevel.setText("Cholestrol Level:");

        lblEcgResult.setText("ECG Result:");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setText("View Vitals Signs");

        lblBloodPressure.setText("Blood Pressure:");

        lblHeartRate.setText("Heart Rate:");

        lblBloodTemp.setText("Body Temperature:");

        lblRespiratoryRate.setText("Respiratory Rate:");

        lblOxygenSaturation.setText("Oxygen Saturation:");

        lblBloodSugarLevel.setText("Blood Sugar Level:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnBack)
                        .addGap(224, 224, 224)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHeartRate)
                            .addComponent(lblBloodPressure)
                            .addComponent(lblBloodTemp)
                            .addComponent(lblRespiratoryRate)
                            .addComponent(lblOxygenSaturation)
                            .addComponent(lblBloodSugarLevel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBodyTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRespiratoryRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOxygenSaturation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBloodSugarLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblWeight)
                            .addComponent(lblHeight)
                            .addComponent(lblBMI)
                            .addComponent(lblPainLevel)
                            .addComponent(lblCholestrolLevel)
                            .addComponent(lblEcgResult))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPainLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCholestrolLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEcgResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblTitle))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBloodPressure)
                            .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHeartRate)
                            .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBloodTemp)
                            .addComponent(txtBodyTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRespiratoryRate)
                            .addComponent(txtRespiratoryRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOxygenSaturation)
                            .addComponent(txtOxygenSaturation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBloodSugarLevel)
                            .addComponent(txtBloodSugarLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHeight)
                            .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWeight)
                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBMI)
                            .addComponent(txtBMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPainLevel)
                            .addComponent(txtPainLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCholestrolLevel)
                            .addComponent(txtCholestrolLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEcgResult)
                            .addComponent(txtEcgResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBloodPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodPressureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodPressureActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void populateVitalSigns() {
        if (vitalSigns != null) {
            txtBloodPressure.setText(String.valueOf(vitalSigns.getBloodPressure()));
            txtHeartRate.setText(String.valueOf(vitalSigns.getHeartRate()));
            txtBodyTemp.setText(String.valueOf(vitalSigns.getBodyTemperature()));
            txtRespiratoryRate.setText(String.valueOf(vitalSigns.getRespiratoryRate()));
            txtOxygenSaturation.setText(String.valueOf(vitalSigns.getOxygenSaturation()));
            txtBloodSugarLevel.setText(String.valueOf(vitalSigns.getBloodSugarLevel()));
            txtHeight.setText(String.valueOf(vitalSigns.getHeight()));
            txtWeight.setText(String.valueOf(vitalSigns.getWeight()));
            txtBMI.setText(String.valueOf(vitalSigns.getBmi()));
            txtPainLevel.setText(String.valueOf(vitalSigns.getPainLevel()));
            txtCholestrolLevel.setText(String.valueOf(vitalSigns.getCholesterolLevel()));
            txtEcgResult.setText(vitalSigns.getEcgResults());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblBMI;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblBloodSugarLevel;
    private javax.swing.JLabel lblBloodTemp;
    private javax.swing.JLabel lblCholestrolLevel;
    private javax.swing.JLabel lblEcgResult;
    private javax.swing.JLabel lblHeartRate;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblOxygenSaturation;
    private javax.swing.JLabel lblPainLevel;
    private javax.swing.JLabel lblRespiratoryRate;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTextField txtBMI;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtBloodSugarLevel;
    private javax.swing.JTextField txtBodyTemp;
    private javax.swing.JTextField txtCholestrolLevel;
    private javax.swing.JTextField txtEcgResult;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtOxygenSaturation;
    private javax.swing.JTextField txtPainLevel;
    private javax.swing.JTextField txtRespiratoryRate;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
